name: "Peimar Inverter Bridge"
version: "1.1.1"
slug: "peimar_bridge"
description: "Recupero dati Inverter Peimar via MQTT"
arch:
  - aarch64
  - amd64
  - armv7
init: false
map:
  - "share:rw"
options:
  peimar_user: ""
  peimar_pass: ""
  mqtt_host: "core-mosquitto"
  mqtt_user: "mqtt"
  mqtt_pass: "mqttpassword"
schema:
  peimar_user: str
  peimar_pass: password
  mqtt_host: str
  mqtt_user: str
  mqtt_pass: password
